# Generated by Django 4.1.5 on 2023-01-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='converted-files/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
